const fs = require('fs');
const path = require('path');

const localesDir = path.join(__dirname, '../client/src/locales');
if (!fs.existsSync(localesDir)) fs.mkdirSync(localesDir, { recursive: true });

const texts = {
    en: {
        nav: { home: "Home", products: "Products", downloads: "Downloads", about: "About", contact: "Contact", getInTouch: "Get in Touch", language: "Language" },
        hero: { subtitle: "Architectural Lighting Excellence", title1: "Precision in ", highlight: "Every", title2: "Profile", desc: "Defining modern spaces with premium aluminum profiles and advanced magnetic track lighting systems.", explore: "Explore Collection", story: "Our Story" },
        brand: { subtitle: "Our Brands", title1: "Two Pillars of ", highlight: "Excellence", plTag: "Aluminum Profiles", plDesc: "Over 300 customizable aluminum profile models with premium finishes.", mlTag: "Magnetic Track Systems & Commercial Lights", mlDesc: "Advanced magnetic track lighting for modern architectural spaces.", view: "View Collection" },
        global: { subtitle: "Worldwide Presence", title1: "Global Export ", highlight: "Network", desc: "We proudly export our lighting solutions to over 100 countries worldwide, delivering premium aluminum profiles and commercial lighting systems to partners across Asia, Europe, the Middle East, Africa, and the Americas.", btn: "Become a Partner", stat1: "Countries Served", stat2: "Global Partners", stat3: "Projects Completed" },
        exhibition: { subtitle: "Meet Us Worldwide", title: "Exhibitions", desc: "We participate in leading lighting exhibitions worldwide, showcasing our latest innovations and connecting with global partners." },
        gallery: { highlight: "Industry", title2: "Applications", desc: "Featuring hundreds of LED linear lighting aluminum profile models with extensive stock of premium materials. The range covers all dimensions.", appLabel: "Application", explore: "Explore", cat: { villa: "Villa and luxury residence", flat: "Super Large Flat Layer", club: "Private club", estate: "Real estate project", office: "Commercial Office Space", hotel: "Five-star plus hotel", apt: "Top Apartment", home: "Ordinary home decoration" } },
        footer: { title1: "Let's Work ", highlight: "Together", addr: "No. 11, Longsha Industrial Zone, Jianghai District, Jiangmen City, Guangdong, China", follow: "Follow Us", desc: "Premium LED aluminum profiles and magnetic track lighting systems, crafted for architects and designers who demand excellence.", privacy: "Privacy Policy", terms: "Terms of Service", rights: "All rights reserved." }
    },
    zh: {
        nav: { home: "首页", products: "产品", downloads: "下载", about: "关于我们", contact: "联系我们", getInTouch: "联系我们", language: "语言" },
        hero: { subtitle: "建筑照明的卓越之选", title1: "精准", highlight: "每一", title2: "细节", desc: "以优质铝型材和先进的磁吸轨道照明系统定义现代空间。", explore: "探索系列", story: "品牌故事" },
        brand: { subtitle: "旗下品牌", title1: "卓越的", highlight: "两大支柱", plTag: "铝型材", plDesc: "超过300种可定制铝型材，搭配高端表面处理。", mlTag: "磁吸轨道系统及商业照明", mlDesc: "专为现代建筑空间设计的先进磁吸照明。", view: "查看详情" },
        global: { subtitle: "全球业务", title1: "全球出口", highlight: "网络", desc: "我们自豪地将照明解决方案出口至全球100多个国家，为亚洲、欧洲、中东、非洲及美洲的合作伙伴提供优质产品。", btn: "成为合作伙伴", stat1: "服务国家", stat2: "全球合作伙伴", stat3: "完成项目" },
        exhibition: { subtitle: "与我们在全球相遇", title: "展会动态", desc: "我们积极参与全球领先的照明展览，展示最新创新成果并连接全球合作伙伴。" },
        gallery: { highlight: "行业", title2: "应用领域", desc: "提供数百款LED线性照明铝型材，备有丰富的优质材料库存。涵盖从精密小型部件到大型型材的所有尺寸。", appLabel: "应用", explore: "探索", cat: { villa: "别墅及豪宅", flat: "超大平层", club: "私人会所", estate: "地产项目", office: "商业办公空间", hotel: "超五星级酒店", apt: "顶级公寓", home: "普通家装" } },
        footer: { title1: "携手", highlight: "合作", addr: "中国广东省江门市江海区龙沙工业区11号", follow: "关注我们", desc: "高端LED铝型材与磁吸轨道照明系统，专为追求卓越的建筑师与设计师打造。", privacy: "隐私政策", terms: "服务条款", rights: "版权所有" }
    },
    vi: {
        nav: { home: "Trang chủ", products: "Sản phẩm", downloads: "Tài liệu", about: "Giới thiệu", contact: "Liên hệ", getInTouch: "Nhận tư vấn", language: "Ngôn ngữ" },
        hero: { subtitle: "Giải pháp chiếu sáng kiến trúc xuất sắc", title1: "Hoàn hảo trong ", highlight: "Mọi", title2: "Chi tiết", desc: "Định hình không gian hiện đại với thanh nhôm cao cấp và hệ thống ray từ tính tiên tiến.", explore: "Khám phá", story: "Câu chuyện" },
        brand: { subtitle: "Thương hiệu của chúng tôi", title1: "Hai trụ cột của sự ", highlight: "Xuất sắc", plTag: "Thanh nhôm Profile", plDesc: "Hơn 300 mẫu nhôm có thể tùy chỉnh với lớp hoàn thiện cao cấp.", mlTag: "Hệ thống ray từ & Đèn thương mại", mlDesc: "Chiếu sáng ray từ tiên tiến cho các không gian kiến trúc hiện đại.", view: "Xem bộ sưu tập" },
        global: { subtitle: "Hiện diện Toàn cầu", title1: "Mạng lưới Xuất khẩu ", highlight: "Toàn cầu", desc: "Chúng tôi tự hào xuất khẩu các giải pháp chiếu sáng tới hơn 100 quốc gia, cung cấp thanh nhôm cao cấp và hệ thống chiếu sáng thương mại cho các đối tác trên toàn cầu.", btn: "Trở thành đối tác", stat1: "Quốc gia", stat2: "Đối tác toàn cầu", stat3: "Dự án hoàn thành" },
        exhibition: { subtitle: "Gặp gỡ chúng tôi trên toàn thế giới", title: "Triển lãm", desc: "Chúng tôi tham gia các triển lãm chiếu sáng hàng đầu trên toàn thế giới, giới thiệu những đổi mới mới nhất và kết nối với các đối tác toàn cầu." },
        gallery: { highlight: "Ứng dụng", title2: "Ngành nghề", desc: "Nổi bật với hàng trăm mẫu nhôm đèn LED tuyến tính và nguồn vật liệu cao cấp phong phú. Dải sản phẩm bao phủ mọi kích thước, từ linh kiện chính xác nhỏ gọn đến thanh nhôm quy mô lớn.", appLabel: "Ứng dụng", explore: "Khám phá", cat: { villa: "Biệt thự và khu dân cư cao cấp", flat: "Căn hộ siêu lớn", club: "Câu lạc bộ tư nhân", estate: "Dự án bất động sản", office: "Không gian văn phòng thương mại", hotel: "Khách sạn năm sao+", apt: "Căn hộ cao cấp", home: "Trang trí nội thất thông thường" } },
        footer: { title1: "Hãy làm việc ", highlight: "Cùng nhau", addr: "Số 11, Khu công nghiệp Long Sa, Quận Giang Hải, Thành phố Giang Môn, Tỉnh Quảng Đông, Trung Quốc", follow: "Theo dõi chúng tôi", desc: "Nhôm LED cao cấp và hệ thống chiếu sáng ray từ, được chế tác dành cho các kiến ​​trúc sư và nhà thiết kế đòi hỏi sự xuất sắc.", privacy: "Chính sách bảo mật", terms: "Điều khoản dịch vụ", rights: "Đã đăng ký bản quyền." }
    },
    hi: {
        nav: { home: "मुख्य पृष्ठ", products: "उत्पाद", downloads: "डाउनलोड", about: "हमारे बारे में", contact: "संपर्क", getInTouch: "संपर्क करें", language: "भाषा" },
        hero: { subtitle: "आर्किटेक्चरल लाइटिंग एक्सीलेंस", title1: "हर ", highlight: "प्रोफ़ाइल", title2: " में सटीकता", desc: "प्रीमियम एल्युमीनियम प्रोफाइल और उन्नत मैग्नेटिक ट्रैक लाइटिंग सिस्टम के साथ आधुनिक स्थानों को परिभाषित करना।", explore: "संग्रह देखें", story: "हमारी कहानी" },
        brand: { subtitle: "हमारे ब्रांड", title1: "उत्कृष्टता के ", highlight: "दो स्तंभ", plTag: "एल्युमिनियम प्रोफाइल", plDesc: "प्रीमियम फिनिश के साथ 300 से अधिक अनुकूलन योग्य एल्यूमीनियम प्रोफ़ाइल मॉडल।", mlTag: "मैग्नेटिक ट्रैक सिस्टम और कमर्शियल लाइट्स", mlDesc: "आधुनिक स्थापत्य स्थानों के लिए उन्नत चुंबकीय ट्रैक प्रकाश व्यवस्था।", view: "संग्रह देखें" },
        global: { subtitle: "विश्वव्यापी उपस्थिति", title1: "वैश्विक निर्यात ", highlight: "नेटवर्क", desc: "हम एशिया, यूरोप, मध्य पूर्व, अफ्रीका और अमेरिका में भागीदारों को प्रीमियम एल्यूमीनियम प्रोफाइल और वाणिज्यिक प्रकाश व्यवस्था प्रदान करते हुए, दुनिया भर के 100 से अधिक देशों में अपने प्रकाश समाधानों का गर्व से निर्यात करते हैं।", btn: "पार्टनर बनें", stat1: "सेवा प्राप्त देश", stat2: "वैश्विक भागीदार", stat3: "पूरी की गई परियोजनाएँ" },
        exhibition: { subtitle: "दुनिया भर में हमसे मिलें", title: "प्रदर्शनी", desc: "हम दुनिया भर में अग्रणी प्रकाश प्रदर्शनियों में भाग लेते हैं, अपने नवीनतम नवाचारों का प्रदर्शन करते हैं और वैश्विक भागीदारों के साथ जुड़ते हैं।" },
        gallery: { highlight: "उद्योग", title2: "अनुप्रयोग", desc: "सैकड़ों एलईडी रैखिक प्रकाश एल्यूमीनियम प्रोफ़ाइल मॉडल के साथ प्रीमियम सामग्री के व्यापक स्टॉक की विशेषता। रेंज सभी आयामों को कवर करती है।", appLabel: "अनुप्रयोग", explore: "अन्वेषण", cat: { villa: "विला और लक्जरी निवास", flat: "सुपर लार्ज फ्लैट लेयर", club: "निजी क्लब", estate: "रियल एस्टेट परियोजना", office: "वाणिज्यिक कार्यालय स्थान", hotel: "फाइव-स्टार प्लस होटल", apt: "टॉप अपार्टमेंट", home: "साधारण घर की सजावट" } },
        footer: { title1: "आइए ", highlight: "साथ मिलकर", addr: "नंबर 11, लोंगशा इंडस्ट्रियल जोन, जियानघई जिला, जियांगमेन सिटी, ग्वांगडोंग, चीन", follow: "हमें फॉलो करें", desc: "प्रीमियम एलईडी एल्यूमीनियम प्रोफाइल और मैग्नेटिक ट्रैक लाइटिंग सिस्टम, उत्कृष्टता की मांग करने वाले आर्किटेक्ट्स और डिजाइनरों के लिए तैयार किया गया है।", privacy: "गोपनीयता नीति", terms: "सेवा की शर्तें", rights: "सर्वाधिकार सुरक्षित।" }
    },
    tr: {
        nav: { home: "Ana Sayfa", products: "Ürünler", downloads: "İndirilenler", about: "Hakkımızda", contact: "İletişim", getInTouch: "Bize Ulaşın", language: "Dil" },
        hero: { subtitle: "Mimari Aydınlatma Mükemmelliği", title1: "Her ", highlight: "Detayda", title2: " Hassasiyet", desc: "Birinci sınıf alüminyum profiller ve gelişmiş manyetik raylı aydınlatma sistemleri ile modern alanları tanımlamak.", explore: "Koleksiyonu Keşfet", story: "Hikayemiz" },
        brand: { subtitle: "Markalarımız", title1: "Mükemmelliğin ", highlight: "İki Sütunu", plTag: "Alüminyum Profiller", plDesc: "Birinci sınıf yüzeylere sahip 300'den fazla özelleştirilebilir alüminyum profil modeli.", mlTag: "Manyetik Ray Sistemleri ve Ticari Işıklar", mlDesc: "Modern mimari alanlar için gelişmiş manyetik raylı aydınlatma.", view: "Koleksiyonu Görüntüle" },
        global: { subtitle: "Dünya Çapında Varlık", title1: "Global İhracat ", highlight: "Ağı", desc: "Asya, Avrupa, Orta Doğu, Afrika ve Amerika'daki ortaklarımıza birinci sınıf alüminyum profiller ve ticari aydınlatma sistemleri sunarak, aydınlatma çözümlerimizi dünya çapında 100'den fazla ülkeye ihraç etmekten gurur duyuyoruz.", btn: "Ortak Olun", stat1: "Hizmet Verilen Ülkeler", stat2: "Küresel Ortaklar", stat3: "Tamamlanan Projeler" },
        exhibition: { subtitle: "Dünya Çapında Bizimle Buluşun", title: "Fuarlar", desc: "En son yeniliklerimizi sergileyen ve küresel ortaklarla bağlantı kuran dünya çapında önde gelen aydınlatma fuarlarına katılıyoruz." },
        gallery: { highlight: "Endüstri", title2: "Uygulamaları", desc: "Geniş premium malzeme stoku ile yüzlerce LED lineer aydınlatma alüminyum profil modeline sahiptir. Kompakt hassas bileşenlerden büyük ölçekli profillere kadar tüm boyutları kapsar.", appLabel: "Uygulama", explore: "Keşfet", cat: { villa: "Villa ve lüks konut", flat: "Süper Geniş Düz Katman", club: "Özel kulüp", estate: "Emlak projesi", office: "Ticari Ofis Alanı", hotel: "Beş yıldız artı otel", apt: "En İyi Daire", home: "Sıradan ev dekorasyonu" } },
        footer: { title1: "Birlikte ", highlight: "Çalışalım", addr: "No. 11, Longsha Sanayi Bölgesi, Jianghai Bölgesi, Jiangmen Şehri, Guangdong, Çin", follow: "Bizi Takip Edin", desc: "Mükemmellik talep eden mimarlar ve tasarımcılar için hazırlanmış birinci sınıf LED alüminyum profiller ve manyetik raylı aydınlatma sistemleri.", privacy: "Gizlilik Politikası", terms: "Hizmet Şartları", rights: "Tüm hakları saklıdır." }
    },
    de: {
        nav: { home: "Startseite", products: "Produkte", downloads: "Downloads", about: "Über uns", contact: "Kontakt", getInTouch: "Kontaktieren Sie uns", language: "Sprache" },
        hero: { subtitle: "Exzellenz in der Architekturbeleuchtung", title1: "Präzision in ", highlight: "Jedem", title2: " Profil", desc: "Moderne Räume definieren mit erstklassigen Aluminiumprofilen und fortschrittlichen magnetischen Stromschienen-Beleuchtungssystemen.", explore: "Kollektion erkunden", story: "Unsere Geschichte" },
        brand: { subtitle: "Unsere Marken", title1: "Zwei Säulen der ", highlight: "Exzellenz", plTag: "Aluminiumprofile", plDesc: "Über 300 anpassbare Aluminiumprofil-Modelle mit erstklassigen Oberflächen.", mlTag: "Magnetische Stromschienensysteme & Gewerbliche Beleuchtung", mlDesc: "Fortschrittliche magnetische Stromschienenbeleuchtung für moderne architektonische Räume.", view: "Kollektion ansehen" },
        global: { subtitle: "Weltweite Präsenz", title1: "Globales Export-", highlight: "netzwerk", desc: "Wir exportieren unsere Beleuchtungslösungen stolz in über 100 Länder weltweit und liefern erstklassige Aluminiumprofile und gewerbliche Beleuchtungssysteme an Partner in ganz Asien, Europa, dem Nahen Osten, Afrika und Amerika.", btn: "Partner werden", stat1: "Bediente Länder", stat2: "Globale Partner", stat3: "Abgeschlossene Projekte" },
        exhibition: { subtitle: "Treffen Sie uns weltweit", title: "Messen", desc: "Wir nehmen an führenden Beleuchtungsmessen weltweit teil, präsentieren unsere neuesten Innovationen und knüpfen Kontakte zu globalen Partnern." },
        gallery: { highlight: "Industrie-", title2: "anwendungen", desc: "Mit Hunderten von LED-Linearbeleuchtungs-Aluminiumprofilmodellen und einem umfangreichen Lager an hochwertigen Materialien. Das Sortiment deckt alle Dimensionen ab.", appLabel: "Anwendung", explore: "Erkunden", cat: { villa: "Villa und Luxusresidenz", flat: "Supergroße Flachebene", club: "Privatclub", estate: "Immobilienprojekt", office: "Gewerbliche Bürofläche", hotel: "Fünf-Sterne-Plus-Hotel", apt: "Top-Wohnung", home: "Gewöhnliche Heimdekoration" } },
        footer: { title1: "Lassen Sie uns ", highlight: "Zusammenarbeiten", addr: "Nr. 11, Longsha Industriegebiet, Bezirk Jianghai, Stadt Jiangmen, Guangdong, China", follow: "Folgen Sie uns", desc: "Erstklassige LED-Aluminiumprofile und magnetische Stromschienen-Beleuchtungssysteme, gefertigt für Architekten und Designer, die Exzellenz verlangen.", privacy: "Datenschutzrichtlinie", terms: "Nutzungsbedingungen", rights: "Alle Rechte vorbehalten." }
    },
    ru: {
        nav: { home: "Главная", products: "Продукты", downloads: "Загрузки", about: "О нас", contact: "Контакты", getInTouch: "Свяжитесь с нами", language: "Язык" },
        hero: { subtitle: "Совершенство архитектурного освещения", title1: "Точность в ", highlight: "Каждой", title2: " Детали", desc: "Определение современных пространств с помощью алюминиевых профилей премиум-класса и передовых магнитных трековых систем освещения.", explore: "Изучить коллекцию", story: "Наша история" },
        brand: { subtitle: "Наши бренды", title1: "Два столпа ", highlight: "Совершенства", plTag: "Алюминиевые профили", plDesc: "Более 300 настраиваемых моделей алюминиевых профилей премиум-класса.", mlTag: "Магнитные трековые системы и коммерческое освещение", mlDesc: "Передовое магнитное трековое освещение для современных архитектурных пространств.", view: "Смотреть коллекцию" },
        global: { subtitle: "Присутствие по всему миру", title1: "Глобальная экспортная ", highlight: "сеть", desc: "Мы с гордостью экспортируем наши решения в области освещения более чем в 100 стран мира, поставляя алюминиевые профили премиум-класса и коммерческие системы освещения партнерам в Азии, Европе, на Ближнем Востоке, в Африке и Америке.", btn: "Стать партнером", stat1: "Стран обслуживания", stat2: "Глобальных партнеров", stat3: "Завершенных проектов" },
        exhibition: { subtitle: "Встречайте нас по всему миру", title: "Выставки", desc: "Мы участвуем в ведущих мировых выставках освещения, демонстрируя наши последние инновации и налаживая связи с глобальными партнерами." },
        gallery: { highlight: "Отраслевые ", title2: "применения", desc: "Сотни моделей алюминиевых профилей для линейного светодиодного освещения с обширным запасом материалов премиум-класса. Ассортимент охватывает все размеры.", appLabel: "Применение", explore: "Изучить", cat: { villa: "Виллы и элитные резиденции", flat: "Сверхбольшие квартиры", club: "Частные клубы", estate: "Проекты недвижимости", office: "Коммерческие офисные помещения", hotel: "Отели пять звезд+", apt: "Квартиры премиум-класса", home: "Обычный домашний декор" } },
        footer: { title1: "Давайте работать ", highlight: "Вместе", addr: "Промышленная зона Лунша, № 11, район Цзянхай, город Цзянмэнь, провинция Гуандун, Китай", follow: "Подписывайтесь на нас", desc: "Алюминиевые светодиодные профили премиум-класса и магнитные трековые системы освещения, созданные для архитекторов и дизайнеров, требующих совершенства.", privacy: "Политика конфиденциальности", terms: "Условия обслуживания", rights: "Все права защищены." }
    },
};

for (const [lang, data] of Object.entries(texts)) {
    fs.writeFileSync(path.join(localesDir, `${lang}.json`), JSON.stringify(data, null, 2));
}
console.log("Locales generated!");
